default: &default
  appid: 'wx5586124b0377b58a'
  secret: '1ecd7bb5501a48f44bb8b07da5c4ab55'
  token:      <%= ENV['wechat_token'] %>
  access_token: "/var/tmp/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key: <%= ENV['wechat_encodingaeskey'] %>
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"

production:
  appid: <%= ENV['wechat_appid'] %>
  secret: <%= ENV['wechat_secret'] %>
  token:      <%= ENV['wechat_token'] %>
  timeout:    30,
  skip_verify_ssl: true
  access_token:  <%= ENV['wechat_access_token'] %>
  encrypt_mode: yes # if true must fill encoding_aes_key
  encoding_aes_key:  <%= ENV['wechat_encodingaeskey'] %>
  jsapi_ticket: <%= ENV['wechat_jsapi_ticket'] %>
  oauth2_cookie_duration: <%= ENV['wechat_oauth2_cookie_duration'] %> # seconds

development:
  <<: *default
  trusted_domain_fullname: "http://ehero.cc"

test:
  <<: *default